color0 #0f131c
color1 #ffb4ab
color2 #51d7ef
color3 #83d3e3
color4 #a9c7ff
color5 #51d7ef
color6 #83d3e3
color7 #dfe2ef
color8 #8891a5
color9 #ffb4ab
color10 #51d7ef
color11 #83d3e3
color12 #a9c7ff
color13 #51d7ef
color14 #83d3e3
color15 #dfe2ef

cursor                #dfe2ef
cursor_text_color     #0f131c
background            #0f131c
foreground            #dfe2ef
selection_foreground  #bdc7dc
selection_background  #3e4758
active_border_color   #51d7ef
inactive_border_color #3e4758
url_color             #51d7ef

active_tab_foreground   #00363e
active_tab_background   #51d7ef
inactive_tab_foreground #bdc7dc
inactive_tab_background #3e4758
cursor_trail_color      #bdc7dc
