color0 #5a413d
color1 #ffb4ab
color2 #ffb4aa
color3 #ffb4aa
color4 #feba50
color5 #ffb4aa
color6 #ffb4aa
color7 #f7ddd9
color8 #a98985
color9 #ffb4ab
color10 #ffb4aa
color11 #ffb4aa
color12 #feba50
color13 #ffb4aa
color14 #ffb4aa
color15 #f7ddd9

cursor                #f7ddd9
cursor_text_color     #1d100e
background            #1d100e
foreground            #f7ddd9
selection_foreground  #e2beb9
selection_background  #5a413d
active_border_color   #ffb4aa
inactive_border_color #5a413d
url_color             #ffb4aa

active_tab_foreground   #690003
active_tab_background   #ffb4aa
inactive_tab_foreground #e2beb9
inactive_tab_background #5a413d
cursor_trail_color      #e2beb9
