color0 #1e100f
color1 #ffb4ab
color2 #faacf9
color3 #edb4ea
color4 #ffb3b0
color5 #faacf9
color6 #edb4ea
color7 #f8dcda
color8 #ad8886
color9 #ffb4ab
color10 #faacf9
color11 #edb4ea
color12 #ffb3b0
color13 #faacf9
color14 #edb4ea
color15 #f8dcda

cursor                #f8dcda
cursor_text_color     #1e100f
background            #1e100f
foreground            #f8dcda
selection_foreground  #e6bdba
selection_background  #5d3f3e
active_border_color   #faacf9
inactive_border_color #5d3f3e
url_color             #faacf9

active_tab_foreground   #521458
active_tab_background   #faacf9
inactive_tab_foreground #e6bdba
inactive_tab_background #5d3f3e
cursor_trail_color      #e6bdba
