# Mode
Mode="Uinput (Smooth)"
# Input Method
InputMethod="Telex 2"
# Output Charset
OutputCharset=Unicode
# Type w to Produce ư
W2U=Everywhere
# Enable Spell Check
SpellCheck=False
# Enable Macro
EnableMacro=False
# Capitalize Macro
CapitalizeMacro=False
# Auto capitalize after sentence-ending punctuation (. ! ? Enter) (experimental)
AutoCapitalizeAfterPunctuation=False
# Double Space to Period (experimental)
DoubleSpaceToPeriod=False
# Auto Restore Keys With Invalid Words
AutoNonVnRestore=False
# Use oà, uý (Instead Of òa, úy)
ModernStyle=False
# Allow Type With More Freedom
FreeMarking=True
# Allow dd To Produce đ When Auto Restore Keys With Invalid Words Is On
DdFreeStyle=True
# Fix Uinput Mode With Ack
FixUinputWithAck=False
# Use Lotus Status Icons
UseLotusIcons=True
# Enable Custom Dictionary
EnableDictionary=False
# Enable Custom Keymap
EnableCustomKeymap=False
# Show Uinput (Smooth)
ShowModeSmooth=True
# Show Uinput (Slow)
ShowModeUinput=True
# Show Minecraft
ShowModeMinecraft=True
# Show Surrounding Text
ShowModeSurroundingText=True
# Show Preedit
ShowModePreedit=True
# Show Emoji Picker
ShowModeEmoji=True
# Show OFF
ShowModeOff=True
# Show Default Typing
ShowModeDefault=True
# Time Format ($TIME in macro)
TimeFormat=%H:%M
# Date Format ($DATE in macro)
DateFormat=%d/%m/%Y
# Icon Color
IconTheme=Auto

[ModeMenuKey]
0=grave

