# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x111509ff
bordercolor = 0x8b9478ff
focuscolor = 0xfcbb4aff
maximizescreencolor = 0xf1be6dff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xb6d086ff
globalcolor = 0x604100ff
overlaycolor = 0x604100ff
