# Brightness
bind=none,XF86MonBrightnessUp,spawn,bash qs -c noctalia-shell ipc call brightness increase
bind=none,XF86MonBrightnessDown,spawn,bash qs -c noctalia-shell ipc call brightness decrease
# Volumes
bind=none,XF86AudioRaiseVolume,spawn,bash qs -c noctalia-shell ipc call volume increase
bind=none,XF86AudioLowerVolume,spawn,bash qs -c noctalia-shell ipc call volume decrease
bind=none,XF86AudioMute,spawn,bash qs -c noctalia-shell ipc call volume muteOutput
bind=none,XF86AudioMicMute,spawn,bash qs -c noctalia-shell ipc call volume muteInput
# Media
bind=none,XF86AudioPlay,spawn,bash qs -c noctalia-shell ipc call media playPause
bind=none,XF86AudioStop,spawn,bash qs -c noctalia-shell ipc call media pause
bind=none,XF86AudioPrev,spawn,bash qs -c noctalia-shell ipc call media previous
bind=none,XF86AudioNext,spawn,bash qs -c noctalia-shell ipc call media next

bind=SUPER,a,spawn,qs -c noctalia-shell ipc call launcher toggle
bind=SUPER+ALT,l,spawn,qs -c noctalia-shell ipc call sessionMenu toggle
