# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x1e100fff
bordercolor = 0xad8886ff
focuscolor = 0xfaacf9ff
maximizescreencolor = 0xedb4eaff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xffb3b0ff
globalcolor = 0x6c2d70ff
overlaycolor = 0x633664ff
