# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x141407ff
bordercolor = 0x929373ff
focuscolor = 0xffb871ff
maximizescreencolor = 0xfdb975ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xc8cc78ff
globalcolor = 0x6a3c00ff
overlaycolor = 0x6a3c01ff
