# Monitor Rules
# Format: monitorrule=NAME,default_mfact,new_is_master,layout_name,tag,view,offsetx,offsety,width,height,refresh_rate
monitorrule=model:AL258F,width:1920,height:1080,refresh:309.997009,x:0,y:0,scale:1,vrr:0

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller,tgmix
tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:tgmix
tagrule=id:3,layout_name:grid
tagrule=id:4,layout_name:deck
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# window rules
windowrule = isfloating:1,appid:kitty-float,width:640,height:360
