# Monitor Rules
# Format: monitorrule=NAME,default_mfact,new_is_master,layout_name,tag,view,offsetx,offsety,width,height,refresh_rate
monitorrule=DP-1,scroller,0,1,0,0,0,0,1920,1080,310
# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
