#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
#exec-once = qs -c noctalia-shell
exec-once = fcitx5 -d
exec-once = /home/sazv/.config/arch-config/modules/windows-managers/hyprlandWM/dotfiles/hypr/scripts/auto-display.sh
