# ==============================================================================
# Hyprland submodule configuration file
# ==============================================================================
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/myPrograms.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/lookAndFeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowsAndWorkspaces.conf

source = /home/sazv/.config/hypr/noctalia/noctalia-colors.conf
