color0 #12131c
color1 #ffb4ab
color2 #6dd2ff
color3 #8ccff0
color4 #bcc2ff
color5 #6dd2ff
color6 #8ccff0
color7 #e2e1ef
color8 #8e8fa6
color9 #ffb4ab
color10 #6dd2ff
color11 #8ccff0
color12 #bcc2ff
color13 #6dd2ff
color14 #8ccff0
color15 #e2e1ef

cursor                #e2e1ef
cursor_text_color     #12131c
background            #12131c
foreground            #e2e1ef
selection_foreground  #c4c5dd
selection_background  #434559
active_border_color   #6dd2ff
inactive_border_color #434559
url_color             #6dd2ff

active_tab_foreground   #003547
active_tab_background   #6dd2ff
inactive_tab_foreground #c4c5dd
inactive_tab_background #434559
cursor_trail_color      #c4c5dd
