color0 #091517
color1 #ffb4ab
color2 #79da9f
color3 #93d5a9
color4 #81d3e0
color5 #79da9f
color6 #93d5a9
color7 #d7e5e7
color8 #7c9599
color9 #ffb4ab
color10 #79da9f
color11 #93d5a9
color12 #81d3e0
color13 #79da9f
color14 #93d5a9
color15 #d7e5e7

cursor                #d7e5e7
cursor_text_color     #091517
background            #091517
foreground            #d7e5e7
selection_foreground  #b1cbd0
selection_background  #334b4f
active_border_color   #79da9f
inactive_border_color #334b4f
url_color             #79da9f

active_tab_foreground   #00391f
active_tab_background   #79da9f
inactive_tab_foreground #b1cbd0
inactive_tab_background #334b4f
cursor_trail_color      #b1cbd0
