color0 #141407
color1 #ffb4ab
color2 #ffb871
color3 #fdb975
color4 #c8cc78
color5 #ffb871
color6 #fdb975
color7 #e5e3cd
color8 #929373
color9 #ffb4ab
color10 #ffb871
color11 #fdb975
color12 #c8cc78
color13 #ffb871
color14 #fdb975
color15 #e5e3cd

cursor                #e5e3cd
cursor_text_color     #141407
background            #141407
foreground            #e5e3cd
selection_foreground  #c9c9a5
selection_background  #47482e
active_border_color   #ffb871
inactive_border_color #47482e
url_color             #ffb871

active_tab_foreground   #4a2800
active_tab_background   #ffb871
inactive_tab_foreground #c9c9a5
inactive_tab_background #47482e
cursor_trail_color      #c9c9a5
