color0 #111509
color1 #ffb4ab
color2 #fcbb4a
color3 #f1be6d
color4 #b6d086
color5 #fcbb4a
color6 #f1be6d
color7 #e1e5d1
color8 #8b9478
color9 #ffb4ab
color10 #fcbb4a
color11 #f1be6d
color12 #b6d086
color13 #fcbb4a
color14 #f1be6d
color15 #e1e5d1

cursor                #e1e5d1
cursor_text_color     #111509
background            #111509
foreground            #e1e5d1
selection_foreground  #c1caab
selection_background  #424a32
active_border_color   #fcbb4a
inactive_border_color #424a32
url_color             #fcbb4a

active_tab_foreground   #432c00
active_tab_background   #fcbb4a
inactive_tab_foreground #c1caab
inactive_tab_background #424a32
cursor_trail_color      #c1caab
