color0 #1e100c
color1 #ffb4ab
color2 #ffade3
color3 #f7b1de
color4 #ffb4a2
color5 #ffade3
color6 #f7b1de
color7 #f9dcd6
color8 #ae887f
color9 #ffb4ab
color10 #ffade3
color11 #f7b1de
color12 #ffb4a2
color13 #ffade3
color14 #f7b1de
color15 #f9dcd6

cursor                #f9dcd6
cursor_text_color     #1e100c
background            #1e100c
foreground            #f9dcd6
selection_foreground  #e7bdb3
selection_background  #5d4038
active_border_color   #ffade3
inactive_border_color #5d4038
url_color             #ffade3

active_tab_foreground   #58114a
active_tab_background   #ffade3
inactive_tab_foreground #e7bdb3
inactive_tab_background #5d4038
cursor_trail_color      #e7bdb3
